# site settings
title: Poznań Tuchołka Karolina
subtitle: Adwokat
description: adwokat Karolina Tuchołka <br/> Rzetelność, skuteczność oraz wysoka kultura pracy. <br/>Reprezentuję klientów indywidualnych, firmy oraz instytucje.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.ptka.pl" # the base hostname & protocol for your site

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# build settings
markdown: kramdown

sass:
  style: compressed
